wandb_version: 1

architecture:
  desc: null
  value: test_dsc_custom
printer:
  desc: null
  value: DNP
morph_type:
  desc: null
  value: Morphing_Diffusion_2024
epochs:
  desc: null
  value: 30
activation:
  desc: null
  value: gelu
predictor_type:
  desc: null
  value: conv
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705991295.03037
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      3:
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
